apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: gosec and snyk sast and sca
on:
  workflow_dispatch: {}
permissions:
  scm-token-own: read
  scm-token-org: read
  id-token: write
jobs:
  scan-and-evaluate:
    steps:
      - name: checkout-source-code
        uses: cloudbees-io/checkout@v2
        with:
          repository: https://github.com/Dev-Org-Hari/webrtc-go
          path: "webrtc-repo"

      # For testing purpose use CBP-40852 branch
      - name: Run Gosec Scan
        id: gosec-step
        uses: cloudbees-io/gosec-plugin@CBP-47541
        with:
            workspace-dir: "webrtc-repo"

      - id: print-gosec-outputs
        name: Print gosec outputs
        uses: docker://alpine:latest
        run: |
          echo "Gosec outputs:"
          echo "Critical: ${{ steps.gosec-step.outputs.critical-count }}"
          echo "Very high: ${{ steps.gosec-step.outputs.very-high-count }}"
          echo "High: ${{ steps.gosec-step.outputs.high-count }}"
          echo "Medium: ${{ steps.gosec-step.outputs.medium-count }}"
          echo "Low: ${{ steps.gosec-step.outputs.low-count }}"
          echo "Policy Subject: ${{ steps.gosec-step.outputs.policy-subject }}"

      # - name: checkout-source-code-1
      #   uses: cloudbees-io/checkout@v2
      #   with:
      #     repository: https://github.com/Dev-Org-Hari/webrtc-go
      #     path: "webrtc-repo"

      - name: Run Sonar Scan
        id: sonar-step
        uses: cloudbees-io/sonarqube-plugin@CBP-47542
        with:
          workspace-dir: "webrtc-repo"
          url: ${{ vars.SONAR_URL }}
          username: ${{ vars.SONAR_USERNAME }}
          password: ${{ secrets.SONAR_PASSWORD }}
                 
      - id: print-sonar-outputs-1
        name: Print-sonar-outputs-1
        uses: docker://alpine:latest
        run: |
          echo "Outputs from upstream Sonar step:"
          echo "Critical count: ${{ steps.sonar-step.outputs.critical-count }}"
          echo "Very high count: ${{ steps.sonar-step.outputs.very-high-count }}"
          echo "High count: ${{ steps.sonar-step.outputs.high-count }}"
          echo "Medium count: ${{ steps.sonar-step.outputs.medium-count }}"
          echo "Low count: ${{ steps.sonar-step.outputs.low-count }}"
          echo "Policy Subject: ${{ steps.sonar-step.outputs.policy-subject }}"


      - name: checkout-source-code
        uses: cloudbees-io/checkout@v2
        with:
          repository: https://github.com/cbc-dev-test/webrtc-go
          path: "cb-webrtc-repo"

      - name: Run Snyk SAST Scan
        id: snyk-sast-step
        uses: cloudbees-io/snyk-sast-plugin@CBP-47541
        with:
          workspace-dir: "cb-webrtc-repo"
          snyk-token: ${{ secrets.SNYK_TOKEN }}
          org-id: ${{ vars.SNYK_ORG_ID }}
          
      - id: print-outputs-from-snyk-sast-step
        name: print outputs from upstream Snyk SAST step
        uses: docker://alpine:latest
        run: |
          echo "Outputs from upstream Snyk SAST step:"
          echo "Critical count: ${{ steps.snyk-sast-step.outputs.critical-count }}"
          echo "Very high count: ${{ steps.snyk-sast-step.outputs.very-high-count }}"
          echo "High count: ${{ steps.snyk-sast-step.outputs.high-count }}"
          echo "Medium count: ${{ steps.snyk-sast-step.outputs.medium-count }}"
          echo "Low count: ${{ steps.snyk-sast-step.outputs.low-count }}"
          echo "Policy Subject: ${{ steps.snyk-sast-step.outputs.policy-subject }}"
      
      # Printing policy subject details for testing purpose
      - id: print-policy-subject
        name: Print Policy subject
        uses: docker://alpine:latest
        run: |

          echo "=== Files in /cloudbees/workspace/policy-store ==="                                                                                                                              
          find "/cloudbees/workspace/policy-store" -type f | while read file; do                                                                                                               
            echo ""                                                                                                                                                               
            echo "File: $file"                                                                                                                                                    
            cat "$file"                                                                                                                                                           
            echo "---"                                                                                                                                                            
          done