apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: sonarqube
on:
  workflow_dispatch: {}
permissions:
  scm-token-own: read
  scm-token-org: read
  id-token: write
jobs:
  scan-and-evaluate:
    steps:
      - name: checkout-source-code
        uses: cloudbees-io/checkout@v2
        with:
          repository: https://github.com/Dev-Org-Hari/webrtc-go
          path: "webrtc-repo"

      - name: Run Sonar Scan
        id: sonar-step
        uses: cloudbees-io/sonarqube-plugin@CBP-47542
        with:
          workspace-dir: "webrtc-repo"
          url: ${{ vars.SONAR_URL }}
          username: ${{ vars.SONAR_USERNAME }}
          password: ${{ secrets.SONAR_PASSWORD }}
                 
      - id: print-sonar-outputs-1
        name: Print-sonar-outputs-1
        uses: docker://alpine:latest
        run: |
          echo "Outputs from upstream Sonar step:"
          echo "Critical count: ${{ steps.sonar-step.outputs.critical-count }}"
          echo "Very high count: ${{ steps.sonar-step.outputs.very-high-count }}"
          echo "High count: ${{ steps.sonar-step.outputs.high-count }}"
          echo "Medium count: ${{ steps.sonar-step.outputs.medium-count }}"
          echo "Low count: ${{ steps.sonar-step.outputs.low-count }}"
          echo "Policy Subject: ${{ steps.sonar-step.outputs.policy-subject }}"

      
      # Printing policy subject details for testing purpose
      - id: print-policy-subject
        name: Print Policy subject
        uses: docker://alpine:latest
        run: |

          echo "=== Files in /cloudbees/workspace/policy-store ==="                                                                                                                              
          find "/cloudbees/workspace/policy-store" -type f | while read file; do                                                                                                               
            echo ""                                                                                                                                                               
            echo "File: $file"                                                                                                                                                    
            cat "$file"                                                                                                                                                           
            echo "---"                                                                                                                                                            
          done